services:
  vault:
    image: hashicorp/vault:1.9.3
    container_name: vault
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      VAULT_ADDR: "http://localhost:8200"
      VAULT_API_ADDR: "http://localhost:8200"
      VAULT_ADDRESS: "http://localhost:8200"
      VAULT_FORMAT: table # or json or yaml
    volumes:
      - ./vault_config:/vault/config
      - ./vault_data:/vault/data
      - ./vault_policies:/vault/policies
      - ./scripts:/vault/scripts
      - ./audit:/vault/audit
    cap_add:
      - IPC_LOCK
    # restart: unless-stopped
    command: vault server -config=/vault/config/config.hcl
